apiVersion: apps/v1
kind: Deployment
metadata:
  name: Healthcare-deploy
  labels:
    app: Healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Healthcare-app
  template:
    metadata:
      labels:
        app: Healthcare-app
    spec:
      containers:
      - name: Healthcare-container
        image: shivanggupta998/Healthcare-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: Healthcare-np-service
  labels:
    app: Healthcare-app
spec:
  selector:
    app: Healthcare-app

  type: NodePort
  ports:
  - nodePort: 31031  
    port: 8082
    targetPort: 8082
